### ISSUE TITLE
Failed to restart container db and getting 'structure needs cleaning' message.

### ISSUE THREAD

**Issue by karlosb** [drud/ddev#2131]
**Describe the bug**
Trying to startup an existing project and db container failing to load due to 'structure needs cleaning' message on 'ddev logs -s db' results output.

**Screenshots**
![1](https://user-images.githubusercontent.com/7140268/77783450-cd2a0880-7050-11ea-89ea-5d892f5f00ce.png)

**Version and configuration information (please complete the following information):**
 - Mac OSX 10.15.4
 - Docker desktop (Mac OSX) v 2.2.0.4
 - ddev version v1.13.1
 - config.yaml contents

APIVersion: v1.13.1
name: define
type: php
docroot: local
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- local.define
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
  - exec: mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS define; GRANT
      ALL ON define.* TO 'db'@'%';"
use_dns_when_possible: false
timezone: Europe/London

**Comment by rfay** [comment]
It looks like your database has become corrupted, judging from we searches about "structure needs cleaning:".

I don't think you're going to be able to export your database, so you'll probably lose it, I hope you have a snapshot or a db dump.

`ddev delete -Oy <projectname>` should fix this. You'll then have to start and re-import (or `ddev restore-snapshot`) to get your database back.

**Comment by karlosb** [comment]
Hi rfay, many thanks for this.

I've tried:
`ddev delete -Oy define`

But I still get an error as follows:
![1](https://user-images.githubusercontent.com/7140268/77788627-85f44580-7059-11ea-9b59-dad3a7338f21.png)
ie.
`could not remove volume define-mariadb: API error (500): remove define-mariadb: error removing volume path '/var/lib/docker/volumes/define-mariadb/_data': unlinkat /var/lib/docker/volumes/define-mariadb/_data/ibtmp1: structure needs cleaning`

**Comment by rfay** [comment]
Wow. OK, `ddev stop` and then `docker volume rm define-mariadb`

**Comment by rfay** [comment]
If you can't `ddev stop` then `docker rm -f $(docker ps -aq)` instead, then delete the volume.

**Comment by karlosb** [comment]
Ah ok I've tried `docker rm -f $(docker ps -aq)` and that has removed on of the duplicate projects, so ddev list still shows one version of 'define' project (so making progress!).

However I've re-tried `docker volume rm define-mariadb` and still get the `Error response from daemon: remove define-mariadb: error removing volume path '/var/lib/docker/volumes/define-mariadb/_data': unlinkat /var/lib/docker/volumes/define-mariadb/_data/ibtmp1: structure needs cleaning`

**Comment by rfay** [comment]
You may have to reset docker to factory defaults!  I've never seen anything like this before!

After you reset to factory defaults, do increase your disk space for Docker from the default. This kind of thing could have been caused by running out of Docker's disk available.

**Comment by karlosb** [comment]
Yeah I thought this might be the case! I have about 28 projects created and I'm assuming I'm going to lose all the databases etc for all these sites?

**Comment by rfay** [comment]
You can easily export or snapshot the other projects if you reset to factory defaults. 

Another approach is to just abandon the "define" project (and its database), change the name in its config.yaml to "define1" and move on. 

But still, check your docker disk space and consider increasing it.

**Comment by karlosb** [comment]
I've just checked the docker disk space and I have the following:
![1](https://user-images.githubusercontent.com/7140268/77790687-2b5ce880-705d-11ea-8ef4-c83509868ae6.png)

**Comment by rfay** [comment]
If that tells the truth (sometimes I distrust docker) you have enough space.

However... Just a wild hare... Resizing has some minor potential to fix your problem.

**Comment by rfay** [comment]
You did already restart docker to see if it would fix it right?

**Comment by karlosb** [comment]
Yeah I've 'restarted Docker' and I still have the issue. I do need to try 'resizing the disk space' to and restarting to see if this helps as suggested. However I'm not 100% sure how to resize the disk image? Which settings do I adjust for this?

**Comment by karlosb** [comment]
Ah it's working!

Your comment on 'resizing' disk space seems to have done the trick!

I resized the disk image slightly (59gb upto 64gb) and restarted and it seems to have done the trick. I re-imorted a copy of the DB and the local site 'define' is running again!

Many thanks for your help on this, very much appreciated! :-)

**Comment by rfay** [comment]
So you can just edit ~/.ddev/global_config.yaml to remove the bad version of "define". There are other ways, but that should work. So should `ddev delete -Oy define` (now). And `ddev stop --unlist define` should also do it.

**Comment by rfay** [comment]
Yay that it's working!

**Comment by karlosb** [comment]
Ah excellent stuff! :smiley:👍

I've edited `~/.ddev/global_config.yaml` and removed the duplicate 'define' project from there as suggested. All back to normal at `ddev list` now!

Many thanks once again for this, it's really much appreciated!

**Comment by rfay** [comment]
So glad it's working for you!
