### ISSUE TITLE
docker-compose version check is incorrect, results in failure on latest docker Edge

### ISSUE THREAD

**Issue by rfay** [drud/ddev#737]
## What happened (or feature request):

Started up Docker for Windows on latest docker-ce edge (18.03)

`
The docker-compose version currently installed does not meet ddev's requirements: 1.20.0-rc2 is less than 1.10.0
`

Obviously the error message is incorrect, and this is a major blocker.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

`ddev version` does not report because of the docker-compose problem. This should also be fixed.

```
C:\Users\rfay\workspace\randyfay.com>docker version
Client:
 Version:       18.03.0-ce-rc3
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    e730959
 Built: Thu Mar  8 20:11:53 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce-rc3
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   e730959
  Built:        Thu Mar  8 20:20:22 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by kostajh** [comment]
I just came here to report this for Docker 4 Mac, `Docker version 18.03.0-ce-rc3, build e730959`, `docker-compose version 1.20.0-rc2, build 8c4af54`

**Comment by rfay** [comment]
Thanks @kostajh - I'm working on a fix for that, think we'll do a quick release when we get it going. If it's happening on mac now too I can do the fix there. Makes life easier.

**Comment by martinkrcho** [comment]
Is there any progress on this?

**Comment by rfay** [comment]
Yes, this was solved for the instance it was involved with a long time ago @martinkrcho - Are you having trouble? If so please let us know what OS and what docker-compose version you're having trouble with `docker-compose version`

**Comment by martinkrcho** [comment]
I am afraid I can't add any more detail. I ended up uninstalling Local (Flywheel), VirtualBox, Docker Toolbox and Docker Desktop on my Windows 10 machine. I did a clean install of Docker Desktop and ddev works fine with the latest version. This might be still an issue with latest ddev and latest Docker Toolbox on Win 10.

**Comment by zuernBernhard** [comment]
Seems to be still an issue:

```
bernhard@bezu-mac ~/Sites/bkkpfalz.localhost (master*) $ ddev version
bgsync        	drud/ddev-bgsync:v1.5.2
cli           	v1.5.2
commit        	v1.5.2
db            	drud/ddev-dbserver:v1.5.2-10.2
dba           	drud/phpmyadmin:v1.5.2
ddev-ssh-agent	drud/ddev-ssh-agent:v1.5.2
docker        	18.09.2
docker-compose	1.24.0-rc1
domain        	ddev.local
router        	drud/ddev-router:v1.5.2
web           	drud/ddev-webserver:v1.5.2
bernhard@bezu-mac ~/Sites/bkkpfalz.localhost (master*) $ ddev start
The docker-compose version currently installed does not meet ddev's requirements: 1.24.0-rc1 is less than 1.21.0
bernhard@bezu-mac ~/Sites/bkkpfalz.localhost (master*) $
```

**Comment by rfay** [comment]
This was fixed in v1.6.0, but you have v1.5.2, if you'll upgrade it should be ok.
