### ISSUE TITLE
php.ini should add switch "-t" for the sendmail-call

### ISSUE THREAD

**Issue by neufeind** [drud/ddev#971]
With ddev and a typo3-project the default of sending a mail from TYPO3 to MailHog is using the sendmail-functionality of php. TYPO3 uses the famous SwiftMailer-component to send mail.

Trying to send a testmail SwiftMailer then fails with an error because it expects either "-bs" or "-t" in the sendmail-commandline. MailHog doesn't seem to care if -t is provided or not.

So let's imho just add "-t" to the sendmail-call in php.ini-files.

**Comment by rfay** [comment]
This was just fixed in https://github.com/drud/ddev/pull/954

**Comment by rfay** [comment]
And thanks for being so proactive and going out to fix it!

**Comment by neufeind** [comment]
You're welcome. I used the installer-script which gave me the latest release (0.20.0) and not master - so your fix was not included. Also you fixed it different (by not using the sendmail-way but switching to SMTP).

Should we maybe still adjust the sendmail-binary-path in php.ini, as some other environment/component might also be using SwiftMailer some day and failing for the same reason?

**Comment by rfay** [comment]
It's a bug in TYPO3 that it even grabs and uses the php.ini setting for sendmail_path (and sendmail does not exist in the web container). The sendmail_path is *correct* in place there. TYPO3 just uses it incorrectly (if configured for 'sendmail' sending), which is the default. mailhog with the args provided there works perfectly as discussed in those issues, TYPO3 (or swiftmailer?) is just doing some overly aggressive and odd things with that.

**Comment by neufeind** [comment]
Well, it's about Swiftmailer imho. They removed (for security-reasons) support for using the php-mail()-function, with SwiftMailer v6. But they still have a possibility to directly use a sendmail-compatible transport by calling a binary. So what TYPO3 does is going and fetching the configured sendmail-command. And that's where things fail - since SwiftMailer does not just execute what is configured but checks the sendmail-command with a strpos() for "-bs" or "-t".
So if you say it "works as configured" (from the mailhog/php-side) then it might be on SwiftMailer to remove their check? But they might feel they are doing it for a good reason :-) But if you suggest I can reach out to them if they maybe want to fix it on the SwiftMailer-side.

**Comment by rfay** [comment]
For TYPO3 and ddev (and Drupal and other CMSes) I think we have this sorted out just fine. But it is really strange what (swiftmailer) did with that config.
